### ISSUE TITLE
Manifest URL not working

### ISSUE THREAD

**Issue by trechriron** [callunaborealis/fvtt-mutants-and-masterminds-3e#3]
It comes up 404 not found.

**Comment by callunaborealis** [comment]
Hi there, thanks for your interest. I can't seem to replicate this, unfortunately. Are you able to provide more details on the steps to get the 404?

<img width="1419" alt="Screenshot 2022-01-10 at 00 30 35" src="https://user-images.githubusercontent.com/59653547/148691588-1e377a1f-7548-4220-82ab-dd06d8975dea.png">

**Comment by callunaborealis** [comment]
@trechriron Try using https://github.com/callunaborealis/fvtt-mutants-and-masterminds-3e/releases/latest/download/system.json instead. The one in the README is broken, I'll change that. It isn't playable at the moment I'm afraid as I stopped working on it after setting up the system.
